# Generated by Django 5.1.7 on 2025-03-25 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(choices=[('qualified', 'Qualified Worker'), ('general', 'General Worker')], default='general', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('job_profession', models.CharField(blank=True, max_length=255, null=True)),
                ('wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('police_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
