# Generated by Django 5.1.7 on 2025-03-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers_board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerDetail',
        ),
    ]
