# Generated by Django 5.1.7 on 2025-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_board', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireoffer',
            name='accepted',
        ),
        migrations.AddField(
            model_name='hireoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
